name: Unity Activation
on: workflow_dispatch
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        id: getLicense
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2021.3.27f1
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: ${{ steps.getLicense.outputs.filePath }}
