name: Build APK

on:
  workflow_dispatch:
  
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK (без лицензии и keystore)
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          androidAppBundle: false
          unityVersion: 2021.3.27f1
          buildMethod: UnityBuilderAction.BuildScript.PerformAndroidBuild
          androidKeystorePass: none
          androidKeyaliasPass: none

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MobileShooter3D.apk
          path: build/Android/*.apk
